### PR TITLE
Fix and test `WriteStateDiffAt`

### LINKED ISSUE #355: `JobStatus` fields need to be exported
https://github.com/cerc-io/go-ethereum/blob/v1.11.5-statediff-v4/statediff/service.go#L163

### PR DESCRIPTION
**Pull request by roysc**
Make the `JobSatus` fields public so it's actually usable, fix and add a basic unit test for the method.

Resolves https://github.com/cerc-io/go-ethereum/issues/355
See https://github.com/cerc-io/go-ethereum/issues/356#issuecomment-1493438343

### CODE REVIEW

File: statediff/service_test.go [hunk 1]
```diff
@@ -200,7 +207,7 @@ func testErrorInBlockLoop(t *testing.T) {
 	}()
 	service.Loop(eventsChannel)
 
-	defaultParams.ComputeWatchedAddressesLeafPaths()
+	// defaultParams.ComputeWatchedAddressesLeafPaths()
```
Comment (i-norden) [inline statediff/service_test.go]: nitpick: remove this comment

File: statediff/service_test.go [hunk 2]
```diff
@@ -275,7 +278,7 @@ func testErrorInStateDiffAt(t *testing.T) {
 		t.Error(err)
 	}
 
-	defaultParams.ComputeWatchedAddressesLeafPaths()
+	// defaultParams.ComputeWatchedAddressesLeafPaths()
```
Comment (i-norden) [inline statediff/service_test.go]: nitpick: same here

**Review by i-norden — APPROVED** [review]
This LGTM, thanks for the quick fix. Can you also apply this on top of [v5](https://github.com/cerc-io/go-ethereum/tree/v1.11.5-statediff-v5)? Once this is merged in I have another fix I want to get in before we cut a new release that https://github.com/cerc-io/eth-statediff-fill-service/pull/18 can use.
